apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta
    kind: Deployment
    name: scalingdemo
  minReplicas: 2
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50
