apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp
        env: frontend
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - image: mysql
        name: mysql-container
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
